### PR TITLE
Disambiguate namespace/class name

### LINKED ISSUE #4: Disambiguate namespace/class name
Using the name `SerilogTraceListener` as both the namespace and class names makes it awkward to resolve in C# code.

I think we need to rename one or the other; I'm not sure if any particular option stands out. Here is one proposal, any alternatives/suggestions would be great.

``` csharp
// assembly: Serilog.Diagnostics
namespace Serilog.Diagnostics
{
    public class SerilogTraceListener: TraceListener
    {
```

Thus `new SerilogTraceListener()` with the namespace generally inferred by VS/ReSharper, and `"Serilog.Diagnostics.TraceListener, Serilog.Diagnostics"` in XML.

(Avoiding NuGet package renames if possible for now.)

It's not necessarily conventional to package _Serilog.Diagnostics.dll_ in _SerilogTraceListener_, but since a) most XML configuration is copy/paste and b) in VS, typing _SerilogTraceListener_ will resolve to the correct class name, I think it'd be fine in practice.

Thoughts?

### PR DESCRIPTION
**Pull request by augustoproiete**
Taking a stab at #4 :

* Moved classes in namespace `SerilogTraceListener` to new namespace `Serilog.Diagnostics`
* Set `RootNamespace` to `Serilog` and use folder structure to define the namespace (_same convention as other Serilog extensions_)
* Set `AssemblyName` to `Serilog.Diagnostics.TraceListener`
* Renamed projects to `Serilog.Diagnostics.TraceListener` and `Serilog.Diagnostics.TraceListener.Tests`
* Renamed solution to `serilog-diagnostics-tracelistener` (_same convention as other Serilog extensions_)
* Updated the README usage examples with the new namespace
* NuGet package remains the same: `SerilogTraceListener` for now

---

#### Usage:

```csharp
using System.Diagnostics;
using Serilog.Diagnostics;

namespace MyConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var listener = new SerilogTraceListener();
            Trace.Listeners.Add(listener);

            // ...
        }
    }
}
```

### CODE REVIEW

**Comment by nblumhardt** [comment]
This is awesome, thank you Caio 👍 

Thinking aloud; since it'll be a breaking change, what would you think if we:

 * Rename the project and package to _Serilog.Diagnostics.TraceListener_, and the repository to `serilog-diagnostics-tracelistener`
 * Go all the way with the package name/namespace correlation, and put the `SerilogTraceListener` type under `Serilog.Diagnostics.TraceListener`
 * Publish it as version `1.0.0-pre`
 * Publish (through a branch build), a `4.0.0-pre` version of _SerilogTraceListener_ that has no code, but instead depends on `1.0.0-pre` of _Serilog.Diagnostics.TraceListener_

?

I.e., we'd essentially turn this into a new package and break ties with the past naming in one hit, leaving people a clue where to look in an eventual `4.0.0` of the old package.

I like the direction you're heading; maybe we also take the plunge and bring this under `serilog`, once we've made the rename?

**Comment by augustoproiete** [comment]
Hey @nblumhardt, somehow I missed the notification on your comment above so only addressing it now, almost a year later :eyes:

Your suggestions all makes sense to me. I didn't know you would want to go all the way in one step (renaming the nuget package), so I stopped at moving the classes to the new namespace, but I agree that it's already a breaking change anyway so why not make the switch.

> * Rename the project and package to _Serilog.Diagnostics.TraceListener_, and the repository to `serilog-diagnostics-tracelistener`

I renamed the project in my initial PR so that's done. Renaming the repository I'll leave to you as I'm not in the org and don't have permissions.

> * Go all the way with the package name/namespace correlation, and put the `SerilogTraceListener` type under `Serilog.Diagnostics.TraceListener`

This is now done in my most recent update to this PR.

> * Publish it as version `1.0.0-pre`

I published an initial `0.0.1-pre` on NuGet (built locally from my dev machine) just to reserve the name, and unlisted it. I've added the [`serilog`](https://www.nuget.org/profiles/serilog) org as owner of the package on nuget.org and it's pending approval. I'll leave it to you to run the AppVeyor build process and release version `1.0.0-pre`

> * Publish (through a branch build), a `4.0.0-pre` version of _SerilogTraceListener_ that has no code, but instead depends on `1.0.0-pre` of _Serilog.Diagnostics.TraceListener_

That's a good idea. A meta-package can help devs find the new package more easily. We should also [mark the package as deprecated now that NuGet supports it](https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages) and link to the new one.

I created an [orphan branch on my fork](https://github.com/augustoproiete-forks/serilog-trace-listener--SerilogTraceListener/tree/rename-package-to-serilog-diagnostics-tracelistener) that creates a meta-package with the dependency to the new `Serilog.Diagnostics.TraceListener.1.0.0-pre` - in theory your AppVeyor pipeline should Just Work™ once `Serilog.Diagnostics.TraceListener.1.0.0-pre` is published on nuget.org (right now it fails the restore given the package doesn't exist yet).

GitHub unfortunately doesn't allow me to send a PR to this repo without having an orphan branch as destination. If you can push an orphan branch to this repo, I can send you a PR.

Alternatively I'm [attaching the `nuspec` here](https://github.com/serilog-trace-listener/SerilogTraceListener/files/5398123/SerilogTraceListener.nuspec.txt) if you decide to package with the nuget CLI directly, instead.

> maybe we also take the plunge and bring this under `serilog`, once we've made the rename?

Yes, that makes sense to me.

---

Attachments:
- [SerilogTraceListener.nuspec](https://github.com/serilog-trace-listener/SerilogTraceListener/files/5398123/SerilogTraceListener.nuspec.txt)

**Comment by nblumhardt** [comment]
😎 great to revive this thread! I'll loop back and try to catch up on it all this week 👍

**Comment by augustoproiete** [comment]
@nblumhardt Thanks for adding me to the org. Please let me know if this PR is ready for merge (or merge it) and I'll move forward with renaming the repo.

**Comment by nblumhardt** [comment]
@augustoproiete thanks for the nudge! I'd be more than happy for you to coordinate and push things forwards, if you are keen - I think I'm likely to be the bottleneck/weakest link otherwise 😄 Let me know if anything gets in the way and I'll jump in.

**Pull request merged**
