### PR TITLE
Make project multi-targeted to net45, net46 and netstandard1.3

### PR DESCRIPTION
**Pull request by hacst**
Try to match the available serilog targets as closely as possible.
Serilog also targets netstandard1.0 but System.Diagnostics.TraceSource
which provides TraceListeners is not available for this target.

netstandard1.3 also does not have something comparable to TraceTransfer
so we only conditionally enable it for net45 and net46. Due to this some
other small parts of codes and a test have to become conditional too.

Modify Build.ps1 to use new 'dotnet' tool instead of raw msbuild and nuget.
Also make it execute the tests before creating the nuget package.

Aims to fix issue #19

Note that I am quite a noob when it comes to .NET so taking a close look at the diff would be prudent.

### CODE REVIEW

**Comment by hacst** [comment]
Still looks like build logging isn't using the special appveyor logger. Also the generated nuget package is not detected. Still think this should be pretty close.

Not sure I can do much better without knowing the specific appveyor setup this project is using (I see no appveyor.yml). Any maintainer feel free to massage this so it can land. I allowed edits. If there is something I can do let me know.

**Comment by nblumhardt** [comment]
appveyor.yml is checked in now - thanks! Dropped out the `customlogger` arg from it as I don't think we're gaining anything from it.

Have you verified that the build system is definitely defining `NET45` and `NET46` on those targets? IIRC they're not defined out of the box, so this code might not be being hit.

**Comment by hacst** [comment]
Yeah. NET45 and NET46 are definitely set. See https://docs.microsoft.com/en-us/dotnet/standard/frameworks which describes what is set for which framework. I took the chance and inverted the condition so even if they weren't it would now just fail.

Also did a somewhat ugly hack to allow appveyor to not overwrite the test results of the different frameworks with each other by making the fixtures name change depending on the framework it is built with. I don't much like abusing the pre-processor that way but it seemed worth it in this case as otherwise the test reporting in appveyor is pretty useless if it is a framework specific problem.

Another thing I stumbled over is that the automatic test discovery in appveyor seems to be a bit broken with netcoreapp. It detects tests and starts nunit3 console which finds the net45 and net46 test binaries. It completely ignores the netcoreapp one though. This can be worked around by running the test from our build script and disabling the automatic discovery.

**Comment by nblumhardt** [comment]
Great, thanks! Merging now.

**Comment by hacst** [comment]
Awesome. Thanks for the quick turnaround.

**Pull request merged**
